In [1]:
import numpy as np
c = np.array([[1,2,3,4], [5,6,7,8],[9,10,11,12],[5,6,7,8],[3,7,8,9]])
c.ndim
print(c.shape)
print(c.dtype)
print(c)

(5, 4)
int32
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [ 5  6  7  8]
 [ 3  7  8  9]]


In [17]:
c[::2,3]

array([ 4, 12,  9])

In [22]:
#diagonal 
np.diag(c)

array([ 1,  6, 11,  8])

In [27]:
#This code snippet converts the odd elements of a numpy array to their negative form using the for loop
arr = np.array([0,2,4,5,3,7,8,9,5,1])
for i in range(len(arr)):
    if arr[i]%2 == 1:
        arr[i] = arr[i] * -1
    else: arr[i] = arr[i]
        
print (arr)
        

[0 2 4 5 3 7 8 9 5 1]
[ 0  2  4 -5 -3 -7  8 -9 -5 -1]


In [32]:
d[d%2 == 1] = -1 * d[d % 2 == 1]
print(d)

[ 0  2  4 -5 -3 -7  8 -9 -5 -1]


In [ ]:
np.add
np.subtract
np.multiply
np.divide
np.log
np.exp
np.cos
np.sqrt
np.square
np.sin
y.dot 

In [45]:
# dot product
e = np.ones(2,3)
print (e)

TypeError: Cannot interpret '3' as a data type