In [1]:
import numpy as np

Task 1: Creating and Manipulating Arrays

In [3]:
#creaing a 1 dimensional array
arr_1D = np.array([0,1,2,3,4,5,6,7,8,9]) 
print(f'1D Arry is: {arr_1D}')


1D Arry is: [0 1 2 3 4 5 6 7 8 9]


In [8]:
#creating a 2 dimensional array WITH 3 rows and 4 columns
arr_2D = np.array([[0,1,2,3],[5,6,7,8],[9,10,11,12]])
print(f'2D Arry is: {arr_2D}')

2D Arry is: [[ 0  1  2  3]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [7]:
#reshaping a 3 by 4 array to 4 by 3
arr_2D_reshape = arr_2D.reshape(4, 3)
print(f'The reshaped array is: {arr_2D_reshape}')

The reshaped array is: [[ 0  1  2]
 [ 3  5  6]
 [ 7  8  9]
 [10 11 12]]


In [11]:
#slicing array
print(f'The first five element of the 1d array is: {arr_1D[:5]}')

The first five element of the 1d array is: [0 1 2 3 4]


In [14]:
#creating array with numpy functions
zero_array = np.zeros([2,3])
print(f'Zeros array: {zero_array}')
one_array = np.ones([3,2])
print(f'Ones array is: {one_array}')


Zeros array: [[0. 0. 0.]
 [0. 0. 0.]]
Ones array is: [[1. 1.]
 [1. 1.]
 [1. 1.]]


Task 2: Array Operations

In [21]:
x1 = np.arange(0,24, 2).reshape(3,4)
#Addition
array_add = np.add(arr_2D, x1)
print(f'Addition: {array_add}')
#Subtraction
array_sub = np.subtract(arr_2D, x1)
print(f'Subtraction: {array_sub}')
#Multiplication
array_mult = np.multiply(arr_2D, x1)
print(f'Multiplication: {array_mult}')
#Division
array_div = np.divide(x1,arr_2D)
print(f'Division: {array_div}')

Addition: [[ 0  3  6  9]
 [13 16 19 22]
 [25 28 31 34]]
Subtraction: [[  0  -1  -2  -3]
 [ -3  -4  -5  -6]
 [ -7  -8  -9 -10]]
Multiplication: [[  0   2   8  18]
 [ 40  60  84 112]
 [144 180 220 264]]
Division: [[       nan 2.         2.         2.        ]
 [1.6        1.66666667 1.71428571 1.75      ]
 [1.77777778 1.8        1.81818182 1.83333333]]


C:\Users\Tobechukwu Odeh\AppData\Local\Temp\ipykernel_11316\4199419655.py:12: RuntimeWarning: invalid value encountered in divide
  array_div = np.divide(x1,arr_2D)


In [26]:
#computing dot product
np.dot(zero_array, arr_2D)

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [30]:
#creating a 3 by 3 identity matrix
np.identity(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [28]:
print(f'the sum of the 1d array is: {np.sum(arr_1D)}')
print(f'The mean value of the 1d array is: {np.mean(arr_1D)}')
print(f'the standard deviation of the 1d array is: {np.std(arr_1D)}')
print(f'the variance of the 1d array is: {np.var(arr_1D)}')

the sum of the 1d array is: 45
The mean value of the 1d array is: 4.5
the standard deviation of the 1d array is: 2.8722813232690143
the variance of the 1d array is: 8.25


Task 3: Boolean Indexing and Filtering

In [34]:
#generating a 15 element 1 digit array
arr_1d_15 = np.random.randint(0,50, size = 15)
print(arr_1d_15)

[ 3 32  8  0 14 18 13 44 20 36 45 26 15 28  8]


In [36]:
arr_greater_25 = arr_1d_15[arr_1d_15 > 25]
print(arr_greater_25)

[32 44 36 45 26 28]


In [40]:
arr_1d_15[arr_1d_15 < 10] =10
print(arr_1d_15)

[10 32 10 10 14 18 13 44 20 36 45 26 15 28 10]


Task 4: Advanced Operations

In [41]:
#creating a 5 by 5 array
arr_25 = np.random.randint(0,50, size = 25).reshape(5,5)
print(arr_25)

[[35 39  4 21 10]
 [ 0 44 26 23 16]
 [38 45 39 49 28]
 [33 27 17 26  1]
 [42  0 21 14 27]]


In [42]:
row_sum = np.sum(arr_25, axis = 1)
print(f'Row wise sum is: {row_sum}')
column_sum = np.sum(arr_25, axis = 0)
print(f'Column wise sum is: {column_sum}')

Row wise sum is: [109 109 199 104 104]
Column wise sum is: [148 155 107 133  82]


In [48]:
#stacking
H_stack = np.hstack((arr_2D,x1))
print(f'The horizontal stacking is: {H_stack}')
V_stack = np.hstack((one_array, x1))
print(f'The vertical stacking is: {V_stack}')

The horizontal stacking is: [[ 0  1  2  3  0  2  4  6]
 [ 5  6  7  8  8 10 12 14]
 [ 9 10 11 12 16 18 20 22]]
The vertical stacking is: [[ 1.  1.  0.  2.  4.  6.]
 [ 1.  1.  8. 10. 12. 14.]
 [ 1.  1. 16. 18. 20. 22.]]
